// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.api.rpc.user;

/**
 * Protobuf type {@code GetListFriendResponse}
 */
public  final class GetListFriendResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetListFriendResponse)
    GetListFriendResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetListFriendResponse.newBuilder() to construct.
  private GetListFriendResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetListFriendResponse() {
    friendId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetListFriendResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              friendId_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            friendId_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        friendId_ = friendId_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return web.api.rpc.user.User.internal_static_GetListFriendResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return web.api.rpc.user.User.internal_static_GetListFriendResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            web.api.rpc.user.GetListFriendResponse.class, web.api.rpc.user.GetListFriendResponse.Builder.class);
  }

  public static final int FRIENDID_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList friendId_;
  /**
   * <code>repeated string friendId = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getFriendIdList() {
    return friendId_;
  }
  /**
   * <code>repeated string friendId = 1;</code>
   */
  public int getFriendIdCount() {
    return friendId_.size();
  }
  /**
   * <code>repeated string friendId = 1;</code>
   */
  public java.lang.String getFriendId(int index) {
    return friendId_.get(index);
  }
  /**
   * <code>repeated string friendId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFriendIdBytes(int index) {
    return friendId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < friendId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, friendId_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < friendId_.size(); i++) {
        dataSize += computeStringSizeNoTag(friendId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFriendIdList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof web.api.rpc.user.GetListFriendResponse)) {
      return super.equals(obj);
    }
    web.api.rpc.user.GetListFriendResponse other = (web.api.rpc.user.GetListFriendResponse) obj;

    boolean result = true;
    result = result && getFriendIdList()
        .equals(other.getFriendIdList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFriendIdCount() > 0) {
      hash = (37 * hash) + FRIENDID_FIELD_NUMBER;
      hash = (53 * hash) + getFriendIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static web.api.rpc.user.GetListFriendResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.api.rpc.user.GetListFriendResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static web.api.rpc.user.GetListFriendResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.api.rpc.user.GetListFriendResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(web.api.rpc.user.GetListFriendResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetListFriendResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetListFriendResponse)
      web.api.rpc.user.GetListFriendResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return web.api.rpc.user.User.internal_static_GetListFriendResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return web.api.rpc.user.User.internal_static_GetListFriendResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              web.api.rpc.user.GetListFriendResponse.class, web.api.rpc.user.GetListFriendResponse.Builder.class);
    }

    // Construct using web.api.rpc.user.GetListFriendResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      friendId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return web.api.rpc.user.User.internal_static_GetListFriendResponse_descriptor;
    }

    public web.api.rpc.user.GetListFriendResponse getDefaultInstanceForType() {
      return web.api.rpc.user.GetListFriendResponse.getDefaultInstance();
    }

    public web.api.rpc.user.GetListFriendResponse build() {
      web.api.rpc.user.GetListFriendResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public web.api.rpc.user.GetListFriendResponse buildPartial() {
      web.api.rpc.user.GetListFriendResponse result = new web.api.rpc.user.GetListFriendResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        friendId_ = friendId_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.friendId_ = friendId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof web.api.rpc.user.GetListFriendResponse) {
        return mergeFrom((web.api.rpc.user.GetListFriendResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(web.api.rpc.user.GetListFriendResponse other) {
      if (other == web.api.rpc.user.GetListFriendResponse.getDefaultInstance()) return this;
      if (!other.friendId_.isEmpty()) {
        if (friendId_.isEmpty()) {
          friendId_ = other.friendId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFriendIdIsMutable();
          friendId_.addAll(other.friendId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      web.api.rpc.user.GetListFriendResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (web.api.rpc.user.GetListFriendResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList friendId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFriendIdIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        friendId_ = new com.google.protobuf.LazyStringArrayList(friendId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFriendIdList() {
      return friendId_.getUnmodifiableView();
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public int getFriendIdCount() {
      return friendId_.size();
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public java.lang.String getFriendId(int index) {
      return friendId_.get(index);
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFriendIdBytes(int index) {
      return friendId_.getByteString(index);
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public Builder setFriendId(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendIdIsMutable();
      friendId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public Builder addFriendId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendIdIsMutable();
      friendId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public Builder addAllFriendId(
        java.lang.Iterable<java.lang.String> values) {
      ensureFriendIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, friendId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public Builder clearFriendId() {
      friendId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string friendId = 1;</code>
     */
    public Builder addFriendIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFriendIdIsMutable();
      friendId_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetListFriendResponse)
  }

  // @@protoc_insertion_point(class_scope:GetListFriendResponse)
  private static final web.api.rpc.user.GetListFriendResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new web.api.rpc.user.GetListFriendResponse();
  }

  public static web.api.rpc.user.GetListFriendResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetListFriendResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetListFriendResponse>() {
    public GetListFriendResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetListFriendResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetListFriendResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetListFriendResponse> getParserForType() {
    return PARSER;
  }

  public web.api.rpc.user.GetListFriendResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

