// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.api.rpc.user;

public interface GetListFriendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetListFriendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string friendId = 1;</code>
   */
  java.util.List<java.lang.String>
      getFriendIdList();
  /**
   * <code>repeated string friendId = 1;</code>
   */
  int getFriendIdCount();
  /**
   * <code>repeated string friendId = 1;</code>
   */
  java.lang.String getFriendId(int index);
  /**
   * <code>repeated string friendId = 1;</code>
   */
  com.google.protobuf.ByteString
      getFriendIdBytes(int index);
}
