// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.api.rpc.user;

public interface GetListFriendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetListFriendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
