// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.api.rpc.user;

/**
 * Protobuf service {@code UserService}
 */
public  abstract class UserService
    implements com.google.protobuf.Service {
  protected UserService() {}

  public interface Interface {
    /**
     * <pre>
     * create a new account, save new email, password and send verification email
     * </pre>
     *
     * <code>rpc Registration(.RegistrationRequestGrpc) returns (.RegistrationResponseGrpc);</code>
     */
    public abstract void registration(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.RegistrationRequestGrpc request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.RegistrationResponseGrpc> done);

    /**
     * <pre>
     * login account
     * </pre>
     *
     * <code>rpc Login(.LoginRequest) returns (.LoginResponse);</code>
     */
    public abstract void login(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.LoginRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.LoginResponse> done);

    /**
     * <pre>
     * Verify email
     * </pre>
     *
     * <code>rpc VerificationTokenRegistration(.ConfirmEmailRequest) returns (.ConfirmEmailResponse);</code>
     */
    public abstract void verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ConfirmEmailRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.ConfirmEmailResponse> done);

    /**
     * <pre>
     * send reset password email
     * </pre>
     *
     * <code>rpc PasswordForgot(.PasswordResetRequest) returns (.PasswordResetResponse);</code>
     */
    public abstract void passwordForgot(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.PasswordResetRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.PasswordResetResponse> done);

    /**
     * <pre>
     * save new password
     * </pre>
     *
     * <code>rpc PasswordReset(.NewPasswordRequest) returns (.NewPasswordResponse);</code>
     */
    public abstract void passwordReset(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.NewPasswordRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.NewPasswordResponse> done);

    /**
     * <pre>
     * register account's information
     * </pre>
     *
     * <code>rpc RegistrationInformation(.RegistrationInformationRequest) returns (.RegistrationInformationResponse);</code>
     */
    public abstract void registrationInformation(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.RegistrationInformationRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.RegistrationInformationResponse> done);

    /**
     * <pre>
     * verify reset password token
     * </pre>
     *
     * <code>rpc VerificationResetPasswordToken(.VerificationResetPasswordTokenRequest) returns (.VerificationResetPasswordTokenResponse);</code>
     */
    public abstract void verificationResetPasswordToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.VerificationResetPasswordTokenRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.VerificationResetPasswordTokenResponse> done);

    /**
     * <pre>
     * filter controller call to user service
     * </pre>
     *
     * <code>rpc GetEmailFromToken(.GetEmailRequest) returns (.GetEmailResponse);</code>
     */
    public abstract void getEmailFromToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetEmailRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.GetEmailResponse> done);

    /**
     * <pre>
     *validate toke
     * </pre>
     *
     * <code>rpc ValidateToken(.ValidateTokenRequest) returns (.ValidateTokenResponse);</code>
     */
    public abstract void validateToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ValidateTokenRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.ValidateTokenResponse> done);

    /**
     * <pre>
     * get all user
     * </pre>
     *
     * <code>rpc GetAllUser(.GetAllUserRequest) returns (.GetAllUserResponse);</code>
     */
    public abstract void getAllUser(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetAllUserRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.GetAllUserResponse> done);

    /**
     * <pre>
     * change user's name
     * </pre>
     *
     * <code>rpc RenameUser(.ChangeUserNameRpcRequest) returns (.ChangeUserNameRpcResponse);</code>
     */
    public abstract void renameUser(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ChangeUserNameRpcRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.ChangeUserNameRpcResponse> done);

    /**
     * <pre>
     * save source user's avatar to DB
     * </pre>
     *
     * <code>rpc SaveAvatar(.SaveUserAvatarRequest) returns (.SaveUserAvatarResponse);</code>
     */
    public abstract void saveAvatar(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.SaveUserAvatarRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.SaveUserAvatarResponse> done);

    /**
     * <pre>
     * get user avatar
     * </pre>
     *
     * <code>rpc getUserAvatar(.GetUserAvatarRequest) returns (.GetUserAvatarResponse);</code>
     */
    public abstract void getUserAvatar(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetUserAvatarRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.GetUserAvatarResponse> done);

    /**
     * <code>rpc getUserInfo(.GetUserInfoRequest) returns (.GetUserInfoResponse);</code>
     */
    public abstract void getUserInfo(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetUserInfoRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.GetUserInfoResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new UserService() {
      @java.lang.Override
      public  void registration(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.RegistrationRequestGrpc request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.RegistrationResponseGrpc> done) {
        impl.registration(controller, request, done);
      }

      @java.lang.Override
      public  void login(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.LoginRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.LoginResponse> done) {
        impl.login(controller, request, done);
      }

      @java.lang.Override
      public  void verificationTokenRegistration(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.ConfirmEmailRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.ConfirmEmailResponse> done) {
        impl.verificationTokenRegistration(controller, request, done);
      }

      @java.lang.Override
      public  void passwordForgot(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.PasswordResetRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.PasswordResetResponse> done) {
        impl.passwordForgot(controller, request, done);
      }

      @java.lang.Override
      public  void passwordReset(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.NewPasswordRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.NewPasswordResponse> done) {
        impl.passwordReset(controller, request, done);
      }

      @java.lang.Override
      public  void registrationInformation(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.RegistrationInformationRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.RegistrationInformationResponse> done) {
        impl.registrationInformation(controller, request, done);
      }

      @java.lang.Override
      public  void verificationResetPasswordToken(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.VerificationResetPasswordTokenRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.VerificationResetPasswordTokenResponse> done) {
        impl.verificationResetPasswordToken(controller, request, done);
      }

      @java.lang.Override
      public  void getEmailFromToken(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.GetEmailRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.GetEmailResponse> done) {
        impl.getEmailFromToken(controller, request, done);
      }

      @java.lang.Override
      public  void validateToken(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.ValidateTokenRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.ValidateTokenResponse> done) {
        impl.validateToken(controller, request, done);
      }

      @java.lang.Override
      public  void getAllUser(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.GetAllUserRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.GetAllUserResponse> done) {
        impl.getAllUser(controller, request, done);
      }

      @java.lang.Override
      public  void renameUser(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.ChangeUserNameRpcRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.ChangeUserNameRpcResponse> done) {
        impl.renameUser(controller, request, done);
      }

      @java.lang.Override
      public  void saveAvatar(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.SaveUserAvatarRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.SaveUserAvatarResponse> done) {
        impl.saveAvatar(controller, request, done);
      }

      @java.lang.Override
      public  void getUserAvatar(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.GetUserAvatarRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.GetUserAvatarResponse> done) {
        impl.getUserAvatar(controller, request, done);
      }

      @java.lang.Override
      public  void getUserInfo(
          com.google.protobuf.RpcController controller,
          web.api.rpc.user.GetUserInfoRequest request,
          com.google.protobuf.RpcCallback<web.api.rpc.user.GetUserInfoResponse> done) {
        impl.getUserInfo(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.registration(controller, (web.api.rpc.user.RegistrationRequestGrpc)request);
          case 1:
            return impl.login(controller, (web.api.rpc.user.LoginRequest)request);
          case 2:
            return impl.verificationTokenRegistration(controller, (web.api.rpc.user.ConfirmEmailRequest)request);
          case 3:
            return impl.passwordForgot(controller, (web.api.rpc.user.PasswordResetRequest)request);
          case 4:
            return impl.passwordReset(controller, (web.api.rpc.user.NewPasswordRequest)request);
          case 5:
            return impl.registrationInformation(controller, (web.api.rpc.user.RegistrationInformationRequest)request);
          case 6:
            return impl.verificationResetPasswordToken(controller, (web.api.rpc.user.VerificationResetPasswordTokenRequest)request);
          case 7:
            return impl.getEmailFromToken(controller, (web.api.rpc.user.GetEmailRequest)request);
          case 8:
            return impl.validateToken(controller, (web.api.rpc.user.ValidateTokenRequest)request);
          case 9:
            return impl.getAllUser(controller, (web.api.rpc.user.GetAllUserRequest)request);
          case 10:
            return impl.renameUser(controller, (web.api.rpc.user.ChangeUserNameRpcRequest)request);
          case 11:
            return impl.saveAvatar(controller, (web.api.rpc.user.SaveUserAvatarRequest)request);
          case 12:
            return impl.getUserAvatar(controller, (web.api.rpc.user.GetUserAvatarRequest)request);
          case 13:
            return impl.getUserInfo(controller, (web.api.rpc.user.GetUserInfoRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.api.rpc.user.RegistrationRequestGrpc.getDefaultInstance();
          case 1:
            return web.api.rpc.user.LoginRequest.getDefaultInstance();
          case 2:
            return web.api.rpc.user.ConfirmEmailRequest.getDefaultInstance();
          case 3:
            return web.api.rpc.user.PasswordResetRequest.getDefaultInstance();
          case 4:
            return web.api.rpc.user.NewPasswordRequest.getDefaultInstance();
          case 5:
            return web.api.rpc.user.RegistrationInformationRequest.getDefaultInstance();
          case 6:
            return web.api.rpc.user.VerificationResetPasswordTokenRequest.getDefaultInstance();
          case 7:
            return web.api.rpc.user.GetEmailRequest.getDefaultInstance();
          case 8:
            return web.api.rpc.user.ValidateTokenRequest.getDefaultInstance();
          case 9:
            return web.api.rpc.user.GetAllUserRequest.getDefaultInstance();
          case 10:
            return web.api.rpc.user.ChangeUserNameRpcRequest.getDefaultInstance();
          case 11:
            return web.api.rpc.user.SaveUserAvatarRequest.getDefaultInstance();
          case 12:
            return web.api.rpc.user.GetUserAvatarRequest.getDefaultInstance();
          case 13:
            return web.api.rpc.user.GetUserInfoRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.api.rpc.user.RegistrationResponseGrpc.getDefaultInstance();
          case 1:
            return web.api.rpc.user.LoginResponse.getDefaultInstance();
          case 2:
            return web.api.rpc.user.ConfirmEmailResponse.getDefaultInstance();
          case 3:
            return web.api.rpc.user.PasswordResetResponse.getDefaultInstance();
          case 4:
            return web.api.rpc.user.NewPasswordResponse.getDefaultInstance();
          case 5:
            return web.api.rpc.user.RegistrationInformationResponse.getDefaultInstance();
          case 6:
            return web.api.rpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance();
          case 7:
            return web.api.rpc.user.GetEmailResponse.getDefaultInstance();
          case 8:
            return web.api.rpc.user.ValidateTokenResponse.getDefaultInstance();
          case 9:
            return web.api.rpc.user.GetAllUserResponse.getDefaultInstance();
          case 10:
            return web.api.rpc.user.ChangeUserNameRpcResponse.getDefaultInstance();
          case 11:
            return web.api.rpc.user.SaveUserAvatarResponse.getDefaultInstance();
          case 12:
            return web.api.rpc.user.GetUserAvatarResponse.getDefaultInstance();
          case 13:
            return web.api.rpc.user.GetUserInfoResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * create a new account, save new email, password and send verification email
   * </pre>
   *
   * <code>rpc Registration(.RegistrationRequestGrpc) returns (.RegistrationResponseGrpc);</code>
   */
  public abstract void registration(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.RegistrationRequestGrpc request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.RegistrationResponseGrpc> done);

  /**
   * <pre>
   * login account
   * </pre>
   *
   * <code>rpc Login(.LoginRequest) returns (.LoginResponse);</code>
   */
  public abstract void login(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.LoginRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.LoginResponse> done);

  /**
   * <pre>
   * Verify email
   * </pre>
   *
   * <code>rpc VerificationTokenRegistration(.ConfirmEmailRequest) returns (.ConfirmEmailResponse);</code>
   */
  public abstract void verificationTokenRegistration(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.ConfirmEmailRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.ConfirmEmailResponse> done);

  /**
   * <pre>
   * send reset password email
   * </pre>
   *
   * <code>rpc PasswordForgot(.PasswordResetRequest) returns (.PasswordResetResponse);</code>
   */
  public abstract void passwordForgot(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.PasswordResetRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.PasswordResetResponse> done);

  /**
   * <pre>
   * save new password
   * </pre>
   *
   * <code>rpc PasswordReset(.NewPasswordRequest) returns (.NewPasswordResponse);</code>
   */
  public abstract void passwordReset(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.NewPasswordRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.NewPasswordResponse> done);

  /**
   * <pre>
   * register account's information
   * </pre>
   *
   * <code>rpc RegistrationInformation(.RegistrationInformationRequest) returns (.RegistrationInformationResponse);</code>
   */
  public abstract void registrationInformation(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.RegistrationInformationRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.RegistrationInformationResponse> done);

  /**
   * <pre>
   * verify reset password token
   * </pre>
   *
   * <code>rpc VerificationResetPasswordToken(.VerificationResetPasswordTokenRequest) returns (.VerificationResetPasswordTokenResponse);</code>
   */
  public abstract void verificationResetPasswordToken(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.VerificationResetPasswordTokenRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.VerificationResetPasswordTokenResponse> done);

  /**
   * <pre>
   * filter controller call to user service
   * </pre>
   *
   * <code>rpc GetEmailFromToken(.GetEmailRequest) returns (.GetEmailResponse);</code>
   */
  public abstract void getEmailFromToken(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.GetEmailRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.GetEmailResponse> done);

  /**
   * <pre>
   *validate toke
   * </pre>
   *
   * <code>rpc ValidateToken(.ValidateTokenRequest) returns (.ValidateTokenResponse);</code>
   */
  public abstract void validateToken(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.ValidateTokenRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.ValidateTokenResponse> done);

  /**
   * <pre>
   * get all user
   * </pre>
   *
   * <code>rpc GetAllUser(.GetAllUserRequest) returns (.GetAllUserResponse);</code>
   */
  public abstract void getAllUser(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.GetAllUserRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.GetAllUserResponse> done);

  /**
   * <pre>
   * change user's name
   * </pre>
   *
   * <code>rpc RenameUser(.ChangeUserNameRpcRequest) returns (.ChangeUserNameRpcResponse);</code>
   */
  public abstract void renameUser(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.ChangeUserNameRpcRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.ChangeUserNameRpcResponse> done);

  /**
   * <pre>
   * save source user's avatar to DB
   * </pre>
   *
   * <code>rpc SaveAvatar(.SaveUserAvatarRequest) returns (.SaveUserAvatarResponse);</code>
   */
  public abstract void saveAvatar(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.SaveUserAvatarRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.SaveUserAvatarResponse> done);

  /**
   * <pre>
   * get user avatar
   * </pre>
   *
   * <code>rpc getUserAvatar(.GetUserAvatarRequest) returns (.GetUserAvatarResponse);</code>
   */
  public abstract void getUserAvatar(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.GetUserAvatarRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.GetUserAvatarResponse> done);

  /**
   * <code>rpc getUserInfo(.GetUserInfoRequest) returns (.GetUserInfoResponse);</code>
   */
  public abstract void getUserInfo(
      com.google.protobuf.RpcController controller,
      web.api.rpc.user.GetUserInfoRequest request,
      com.google.protobuf.RpcCallback<web.api.rpc.user.GetUserInfoResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return web.api.rpc.user.User.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.registration(controller, (web.api.rpc.user.RegistrationRequestGrpc)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.RegistrationResponseGrpc>specializeCallback(
            done));
        return;
      case 1:
        this.login(controller, (web.api.rpc.user.LoginRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.LoginResponse>specializeCallback(
            done));
        return;
      case 2:
        this.verificationTokenRegistration(controller, (web.api.rpc.user.ConfirmEmailRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.ConfirmEmailResponse>specializeCallback(
            done));
        return;
      case 3:
        this.passwordForgot(controller, (web.api.rpc.user.PasswordResetRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.PasswordResetResponse>specializeCallback(
            done));
        return;
      case 4:
        this.passwordReset(controller, (web.api.rpc.user.NewPasswordRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.NewPasswordResponse>specializeCallback(
            done));
        return;
      case 5:
        this.registrationInformation(controller, (web.api.rpc.user.RegistrationInformationRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.RegistrationInformationResponse>specializeCallback(
            done));
        return;
      case 6:
        this.verificationResetPasswordToken(controller, (web.api.rpc.user.VerificationResetPasswordTokenRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.VerificationResetPasswordTokenResponse>specializeCallback(
            done));
        return;
      case 7:
        this.getEmailFromToken(controller, (web.api.rpc.user.GetEmailRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.GetEmailResponse>specializeCallback(
            done));
        return;
      case 8:
        this.validateToken(controller, (web.api.rpc.user.ValidateTokenRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.ValidateTokenResponse>specializeCallback(
            done));
        return;
      case 9:
        this.getAllUser(controller, (web.api.rpc.user.GetAllUserRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.GetAllUserResponse>specializeCallback(
            done));
        return;
      case 10:
        this.renameUser(controller, (web.api.rpc.user.ChangeUserNameRpcRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.ChangeUserNameRpcResponse>specializeCallback(
            done));
        return;
      case 11:
        this.saveAvatar(controller, (web.api.rpc.user.SaveUserAvatarRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.SaveUserAvatarResponse>specializeCallback(
            done));
        return;
      case 12:
        this.getUserAvatar(controller, (web.api.rpc.user.GetUserAvatarRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.GetUserAvatarResponse>specializeCallback(
            done));
        return;
      case 13:
        this.getUserInfo(controller, (web.api.rpc.user.GetUserInfoRequest)request,
          com.google.protobuf.RpcUtil.<web.api.rpc.user.GetUserInfoResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.api.rpc.user.RegistrationRequestGrpc.getDefaultInstance();
      case 1:
        return web.api.rpc.user.LoginRequest.getDefaultInstance();
      case 2:
        return web.api.rpc.user.ConfirmEmailRequest.getDefaultInstance();
      case 3:
        return web.api.rpc.user.PasswordResetRequest.getDefaultInstance();
      case 4:
        return web.api.rpc.user.NewPasswordRequest.getDefaultInstance();
      case 5:
        return web.api.rpc.user.RegistrationInformationRequest.getDefaultInstance();
      case 6:
        return web.api.rpc.user.VerificationResetPasswordTokenRequest.getDefaultInstance();
      case 7:
        return web.api.rpc.user.GetEmailRequest.getDefaultInstance();
      case 8:
        return web.api.rpc.user.ValidateTokenRequest.getDefaultInstance();
      case 9:
        return web.api.rpc.user.GetAllUserRequest.getDefaultInstance();
      case 10:
        return web.api.rpc.user.ChangeUserNameRpcRequest.getDefaultInstance();
      case 11:
        return web.api.rpc.user.SaveUserAvatarRequest.getDefaultInstance();
      case 12:
        return web.api.rpc.user.GetUserAvatarRequest.getDefaultInstance();
      case 13:
        return web.api.rpc.user.GetUserInfoRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.api.rpc.user.RegistrationResponseGrpc.getDefaultInstance();
      case 1:
        return web.api.rpc.user.LoginResponse.getDefaultInstance();
      case 2:
        return web.api.rpc.user.ConfirmEmailResponse.getDefaultInstance();
      case 3:
        return web.api.rpc.user.PasswordResetResponse.getDefaultInstance();
      case 4:
        return web.api.rpc.user.NewPasswordResponse.getDefaultInstance();
      case 5:
        return web.api.rpc.user.RegistrationInformationResponse.getDefaultInstance();
      case 6:
        return web.api.rpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance();
      case 7:
        return web.api.rpc.user.GetEmailResponse.getDefaultInstance();
      case 8:
        return web.api.rpc.user.ValidateTokenResponse.getDefaultInstance();
      case 9:
        return web.api.rpc.user.GetAllUserResponse.getDefaultInstance();
      case 10:
        return web.api.rpc.user.ChangeUserNameRpcResponse.getDefaultInstance();
      case 11:
        return web.api.rpc.user.SaveUserAvatarResponse.getDefaultInstance();
      case 12:
        return web.api.rpc.user.GetUserAvatarResponse.getDefaultInstance();
      case 13:
        return web.api.rpc.user.GetUserInfoResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends web.api.rpc.user.UserService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void registration(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.RegistrationRequestGrpc request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.RegistrationResponseGrpc> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.api.rpc.user.RegistrationResponseGrpc.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.RegistrationResponseGrpc.class,
          web.api.rpc.user.RegistrationResponseGrpc.getDefaultInstance()));
    }

    public  void login(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.LoginRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.LoginResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.api.rpc.user.LoginResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.LoginResponse.class,
          web.api.rpc.user.LoginResponse.getDefaultInstance()));
    }

    public  void verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ConfirmEmailRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.ConfirmEmailResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        web.api.rpc.user.ConfirmEmailResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.ConfirmEmailResponse.class,
          web.api.rpc.user.ConfirmEmailResponse.getDefaultInstance()));
    }

    public  void passwordForgot(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.PasswordResetRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.PasswordResetResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        web.api.rpc.user.PasswordResetResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.PasswordResetResponse.class,
          web.api.rpc.user.PasswordResetResponse.getDefaultInstance()));
    }

    public  void passwordReset(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.NewPasswordRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.NewPasswordResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        web.api.rpc.user.NewPasswordResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.NewPasswordResponse.class,
          web.api.rpc.user.NewPasswordResponse.getDefaultInstance()));
    }

    public  void registrationInformation(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.RegistrationInformationRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.RegistrationInformationResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(5),
        controller,
        request,
        web.api.rpc.user.RegistrationInformationResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.RegistrationInformationResponse.class,
          web.api.rpc.user.RegistrationInformationResponse.getDefaultInstance()));
    }

    public  void verificationResetPasswordToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.VerificationResetPasswordTokenRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.VerificationResetPasswordTokenResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(6),
        controller,
        request,
        web.api.rpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.VerificationResetPasswordTokenResponse.class,
          web.api.rpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance()));
    }

    public  void getEmailFromToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetEmailRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.GetEmailResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(7),
        controller,
        request,
        web.api.rpc.user.GetEmailResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.GetEmailResponse.class,
          web.api.rpc.user.GetEmailResponse.getDefaultInstance()));
    }

    public  void validateToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ValidateTokenRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.ValidateTokenResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(8),
        controller,
        request,
        web.api.rpc.user.ValidateTokenResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.ValidateTokenResponse.class,
          web.api.rpc.user.ValidateTokenResponse.getDefaultInstance()));
    }

    public  void getAllUser(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetAllUserRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.GetAllUserResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(9),
        controller,
        request,
        web.api.rpc.user.GetAllUserResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.GetAllUserResponse.class,
          web.api.rpc.user.GetAllUserResponse.getDefaultInstance()));
    }

    public  void renameUser(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ChangeUserNameRpcRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.ChangeUserNameRpcResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(10),
        controller,
        request,
        web.api.rpc.user.ChangeUserNameRpcResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.ChangeUserNameRpcResponse.class,
          web.api.rpc.user.ChangeUserNameRpcResponse.getDefaultInstance()));
    }

    public  void saveAvatar(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.SaveUserAvatarRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.SaveUserAvatarResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(11),
        controller,
        request,
        web.api.rpc.user.SaveUserAvatarResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.SaveUserAvatarResponse.class,
          web.api.rpc.user.SaveUserAvatarResponse.getDefaultInstance()));
    }

    public  void getUserAvatar(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetUserAvatarRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.GetUserAvatarResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(12),
        controller,
        request,
        web.api.rpc.user.GetUserAvatarResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.GetUserAvatarResponse.class,
          web.api.rpc.user.GetUserAvatarResponse.getDefaultInstance()));
    }

    public  void getUserInfo(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetUserInfoRequest request,
        com.google.protobuf.RpcCallback<web.api.rpc.user.GetUserInfoResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(13),
        controller,
        request,
        web.api.rpc.user.GetUserInfoResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.api.rpc.user.GetUserInfoResponse.class,
          web.api.rpc.user.GetUserInfoResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public web.api.rpc.user.RegistrationResponseGrpc registration(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.RegistrationRequestGrpc request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.LoginResponse login(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.LoginRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.ConfirmEmailResponse verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ConfirmEmailRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.PasswordResetResponse passwordForgot(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.PasswordResetRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.NewPasswordResponse passwordReset(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.NewPasswordRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.RegistrationInformationResponse registrationInformation(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.RegistrationInformationRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.VerificationResetPasswordTokenResponse verificationResetPasswordToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.VerificationResetPasswordTokenRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.GetEmailResponse getEmailFromToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetEmailRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.ValidateTokenResponse validateToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ValidateTokenRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.GetAllUserResponse getAllUser(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetAllUserRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.ChangeUserNameRpcResponse renameUser(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ChangeUserNameRpcRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.SaveUserAvatarResponse saveAvatar(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.SaveUserAvatarRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.GetUserAvatarResponse getUserAvatar(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetUserAvatarRequest request)
        throws com.google.protobuf.ServiceException;

    public web.api.rpc.user.GetUserInfoResponse getUserInfo(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetUserInfoRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public web.api.rpc.user.RegistrationResponseGrpc registration(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.RegistrationRequestGrpc request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.RegistrationResponseGrpc) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.api.rpc.user.RegistrationResponseGrpc.getDefaultInstance());
    }


    public web.api.rpc.user.LoginResponse login(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.LoginRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.LoginResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.api.rpc.user.LoginResponse.getDefaultInstance());
    }


    public web.api.rpc.user.ConfirmEmailResponse verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ConfirmEmailRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.ConfirmEmailResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        web.api.rpc.user.ConfirmEmailResponse.getDefaultInstance());
    }


    public web.api.rpc.user.PasswordResetResponse passwordForgot(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.PasswordResetRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.PasswordResetResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        web.api.rpc.user.PasswordResetResponse.getDefaultInstance());
    }


    public web.api.rpc.user.NewPasswordResponse passwordReset(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.NewPasswordRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.NewPasswordResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        web.api.rpc.user.NewPasswordResponse.getDefaultInstance());
    }


    public web.api.rpc.user.RegistrationInformationResponse registrationInformation(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.RegistrationInformationRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.RegistrationInformationResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(5),
        controller,
        request,
        web.api.rpc.user.RegistrationInformationResponse.getDefaultInstance());
    }


    public web.api.rpc.user.VerificationResetPasswordTokenResponse verificationResetPasswordToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.VerificationResetPasswordTokenRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.VerificationResetPasswordTokenResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(6),
        controller,
        request,
        web.api.rpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance());
    }


    public web.api.rpc.user.GetEmailResponse getEmailFromToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetEmailRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.GetEmailResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(7),
        controller,
        request,
        web.api.rpc.user.GetEmailResponse.getDefaultInstance());
    }


    public web.api.rpc.user.ValidateTokenResponse validateToken(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ValidateTokenRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.ValidateTokenResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(8),
        controller,
        request,
        web.api.rpc.user.ValidateTokenResponse.getDefaultInstance());
    }


    public web.api.rpc.user.GetAllUserResponse getAllUser(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetAllUserRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.GetAllUserResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(9),
        controller,
        request,
        web.api.rpc.user.GetAllUserResponse.getDefaultInstance());
    }


    public web.api.rpc.user.ChangeUserNameRpcResponse renameUser(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.ChangeUserNameRpcRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.ChangeUserNameRpcResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(10),
        controller,
        request,
        web.api.rpc.user.ChangeUserNameRpcResponse.getDefaultInstance());
    }


    public web.api.rpc.user.SaveUserAvatarResponse saveAvatar(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.SaveUserAvatarRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.SaveUserAvatarResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(11),
        controller,
        request,
        web.api.rpc.user.SaveUserAvatarResponse.getDefaultInstance());
    }


    public web.api.rpc.user.GetUserAvatarResponse getUserAvatar(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetUserAvatarRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.GetUserAvatarResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(12),
        controller,
        request,
        web.api.rpc.user.GetUserAvatarResponse.getDefaultInstance());
    }


    public web.api.rpc.user.GetUserInfoResponse getUserInfo(
        com.google.protobuf.RpcController controller,
        web.api.rpc.user.GetUserInfoRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.api.rpc.user.GetUserInfoResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(13),
        controller,
        request,
        web.api.rpc.user.GetUserInfoResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:UserService)
}

