// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.api.rpc.user;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationRequestGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationRequestGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationResponseGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationResponseGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfirmEmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfirmEmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfirmEmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfirmEmailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PasswordResetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PasswordResetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PasswordResetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PasswordResetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationInformationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationInformationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationInformationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationInformationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewPasswordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewPasswordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewPasswordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewPasswordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VerificationResetPasswordTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VerificationResetPasswordTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VerificationResetPasswordTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VerificationResetPasswordTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetEmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetEmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetEmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetEmailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidateTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidateTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidateTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidateTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllUserResponse_UserGrpcModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllUserResponse_UserGrpcModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeUserNameRpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeUserNameRpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeUserNameRpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeUserNameRpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveUserAvatarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveUserAvatarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveUserAvatarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveUserAvatarResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserAvatarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserAvatarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserAvatarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserAvatarResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserNameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserPots_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserPots_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"H\n\027RegistrationRequestGrpc\022" +
      "\r\n\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\014\n\004name" +
      "\030\003 \001(\t\"9\n\030RegistrationResponseGrpc\022\r\n\005em" +
      "ail\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\"$\n\023ConfirmEmai" +
      "lRequest\022\r\n\005token\030\001 \001(\t\"5\n\024ConfirmEmailR" +
      "esponse\022\016\n\006status\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\"%" +
      "\n\024PasswordResetRequest\022\r\n\005email\030\001 \001(\t\"6\n" +
      "\025PasswordResetResponse\022\016\n\006status\030\001 \001(\t\022\r" +
      "\n\005email\030\002 \001(\t\"P\n\036RegistrationInformation" +
      "Request\022\r\n\005email\030\001 \001(\t\022\020\n\010userName\030\002 \001(\t" +
      "\022\r\n\005phone\030\003 \001(\t\"1\n\037RegistrationInformati" +
      "onResponse\022\016\n\006status\030\001 \001(\t\"/\n\014LoginReque" +
      "st\022\r\n\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"P\n\rL" +
      "oginResponse\022\016\n\006status\030\001 \001(\t\022\r\n\005token\030\002 " +
      "\001(\t\022\020\n\010username\030\003 \001(\t\022\016\n\006userId\030\004 \001(\t\"T\n" +
      "\022NewPasswordRequest\022\r\n\005token\030\001 \001(\t\022\023\n\013ne" +
      "wPassword\030\002 \001(\t\022\032\n\022newPasswordConfirm\030\003 " +
      "\001(\t\"4\n\023NewPasswordResponse\022\r\n\005email\030\001 \001(" +
      "\t\022\016\n\006status\030\002 \001(\t\"6\n%VerificationResetPa" +
      "sswordTokenRequest\022\r\n\005token\030\001 \001(\t\"G\n&Ver" +
      "ificationResetPasswordTokenResponse\022\r\n\005e" +
      "mail\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\" \n\017GetEmailRe" +
      "quest\022\r\n\005token\030\001 \001(\t\"!\n\020GetEmailResponse" +
      "\022\r\n\005email\030\001 \001(\t\"4\n\024ValidateTokenRequest\022" +
      "\r\n\005email\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\"\'\n\025Validat" +
      "eTokenResponse\022\016\n\006status\030\001 \001(\010\"!\n\021GetAll" +
      "UserRequest\022\014\n\004page\030\001 \001(\005\"\212\001\n\022GetAllUser" +
      "Response\0222\n\007allUser\030\001 \003(\0132!.GetAllUserRe" +
      "sponse.UserGrpcModel\032@\n\rUserGrpcModel\022\n\n" +
      "\002id\030\001 \001(\t\022\021\n\tfirstName\030\002 \001(\t\022\020\n\010lastName" +
      "\030\003 \001(\t\"<\n\030ChangeUserNameRpcRequest\022\020\n\010us" +
      "ername\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\"+\n\031ChangeUs" +
      "erNameRpcResponse\022\016\n\006status\030\001 \001(\t\"<\n\025Sav" +
      "eUserAvatarRequest\022\023\n\013imageSource\030\001 \001(\t\022" +
      "\016\n\006userId\030\002 \001(\t\"(\n\026SaveUserAvatarRespons" +
      "e\022\016\n\006status\030\001 \001(\t\"&\n\024GetUserAvatarReques" +
      "t\022\016\n\006userId\030\001 \001(\t\"\'\n\025GetUserAvatarRespon" +
      "se\022\016\n\006avatar\030\001 \001(\t\"$\n\022GetUserInfoRequest" +
      "\022\016\n\006userId\030\001 \001(\t\"$\n\022GetUserNameRequest\022\016" +
      "\n\006userId\030\001 \001(\t\"\'\n\023GetUserNameResponse\022\020\n" +
      "\010userName\030\001 \001(\t\"\252\001\n\023GetUserInfoResponse\022" +
      "\020\n\010userName\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\017\n\007count" +
      "ry\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\016\n\006avatar\030" +
      "\005 \001(\t\022\021\n\tfollowing\030\006 \003(\t\022\021\n\tfollowers\030\007 " +
      "\003(\t\022\027\n\004pots\030\010 \003(\0132\t.UserPots\")\n\010UserPots" +
      "\022\016\n\006potsId\030\001 \001(\t\022\r\n\005image\030\002 \001(\t2\377\007\n\013User" +
      "Service\022C\n\014Registration\022\030.RegistrationRe" +
      "questGrpc\032\031.RegistrationResponseGrpc\022&\n\005" +
      "Login\022\r.LoginRequest\032\016.LoginResponse\022L\n\035" +
      "VerificationTokenRegistration\022\024.ConfirmE" +
      "mailRequest\032\025.ConfirmEmailResponse\022?\n\016Pa" +
      "sswordForgot\022\025.PasswordResetRequest\032\026.Pa" +
      "sswordResetResponse\022:\n\rPasswordReset\022\023.N" +
      "ewPasswordRequest\032\024.NewPasswordResponse\022" +
      "\\\n\027RegistrationInformation\022\037.Registratio" +
      "nInformationRequest\032 .RegistrationInform" +
      "ationResponse\022q\n\036VerificationResetPasswo" +
      "rdToken\022&.VerificationResetPasswordToken" +
      "Request\032\'.VerificationResetPasswordToken" +
      "Response\0228\n\021GetEmailFromToken\022\020.GetEmail" +
      "Request\032\021.GetEmailResponse\022>\n\rValidateTo" +
      "ken\022\025.ValidateTokenRequest\032\026.ValidateTok" +
      "enResponse\0225\n\nGetAllUser\022\022.GetAllUserReq" +
      "uest\032\023.GetAllUserResponse\022C\n\nRenameUser\022" +
      "\031.ChangeUserNameRpcRequest\032\032.ChangeUserN" +
      "ameRpcResponse\022=\n\nSaveAvatar\022\026.SaveUserA" +
      "vatarRequest\032\027.SaveUserAvatarResponse\022>\n" +
      "\rgetUserAvatar\022\025.GetUserAvatarRequest\032\026." +
      "GetUserAvatarResponse\0228\n\013getUserInfo\022\023.G" +
      "etUserInfoRequest\032\024.GetUserInfoResponse\022" +
      "8\n\013getUserName\022\023.GetUserNameRequest\032\024.Ge" +
      "tUserNameResponseB\027\n\020web.api.rpc.userP\001\210" +
      "\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RegistrationRequestGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegistrationRequestGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationRequestGrpc_descriptor,
        new java.lang.String[] { "Email", "Password", "Name", });
    internal_static_RegistrationResponseGrpc_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RegistrationResponseGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationResponseGrpc_descriptor,
        new java.lang.String[] { "Email", "Status", });
    internal_static_ConfirmEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ConfirmEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfirmEmailRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_ConfirmEmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ConfirmEmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfirmEmailResponse_descriptor,
        new java.lang.String[] { "Status", "Email", });
    internal_static_PasswordResetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PasswordResetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PasswordResetRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_PasswordResetResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PasswordResetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PasswordResetResponse_descriptor,
        new java.lang.String[] { "Status", "Email", });
    internal_static_RegistrationInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_RegistrationInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationInformationRequest_descriptor,
        new java.lang.String[] { "Email", "UserName", "Phone", });
    internal_static_RegistrationInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_RegistrationInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationInformationResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "Status", "Token", "Username", "UserId", });
    internal_static_NewPasswordRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_NewPasswordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewPasswordRequest_descriptor,
        new java.lang.String[] { "Token", "NewPassword", "NewPasswordConfirm", });
    internal_static_NewPasswordResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_NewPasswordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewPasswordResponse_descriptor,
        new java.lang.String[] { "Email", "Status", });
    internal_static_VerificationResetPasswordTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_VerificationResetPasswordTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VerificationResetPasswordTokenRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_VerificationResetPasswordTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_VerificationResetPasswordTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VerificationResetPasswordTokenResponse_descriptor,
        new java.lang.String[] { "Email", "Status", });
    internal_static_GetEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_GetEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetEmailRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_GetEmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_GetEmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetEmailResponse_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_ValidateTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ValidateTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidateTokenRequest_descriptor,
        new java.lang.String[] { "Email", "Token", });
    internal_static_ValidateTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_ValidateTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidateTokenResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_GetAllUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_GetAllUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllUserRequest_descriptor,
        new java.lang.String[] { "Page", });
    internal_static_GetAllUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_GetAllUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllUserResponse_descriptor,
        new java.lang.String[] { "AllUser", });
    internal_static_GetAllUserResponse_UserGrpcModel_descriptor =
      internal_static_GetAllUserResponse_descriptor.getNestedTypes().get(0);
    internal_static_GetAllUserResponse_UserGrpcModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllUserResponse_UserGrpcModel_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", });
    internal_static_ChangeUserNameRpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_ChangeUserNameRpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeUserNameRpcRequest_descriptor,
        new java.lang.String[] { "Username", "UserId", });
    internal_static_ChangeUserNameRpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_ChangeUserNameRpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeUserNameRpcResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_SaveUserAvatarRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_SaveUserAvatarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveUserAvatarRequest_descriptor,
        new java.lang.String[] { "ImageSource", "UserId", });
    internal_static_SaveUserAvatarResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_SaveUserAvatarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveUserAvatarResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_GetUserAvatarRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_GetUserAvatarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserAvatarRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_GetUserAvatarResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_GetUserAvatarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserAvatarResponse_descriptor,
        new java.lang.String[] { "Avatar", });
    internal_static_GetUserInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_GetUserInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserInfoRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_GetUserNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_GetUserNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserNameRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_GetUserNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_GetUserNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserNameResponse_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_GetUserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_GetUserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserInfoResponse_descriptor,
        new java.lang.String[] { "UserName", "City", "Country", "Description", "Avatar", "Following", "Followers", "Pots", });
    internal_static_UserPots_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_UserPots_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserPots_descriptor,
        new java.lang.String[] { "PotsId", "Image", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
