// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.api.rpc.newsfeed;

public interface CommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string userAvatar = 3;</code>
   */
  java.lang.String getUserAvatar();
  /**
   * <code>string userAvatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserAvatarBytes();

  /**
   * <code>string timeComment = 4;</code>
   */
  java.lang.String getTimeComment();
  /**
   * <code>string timeComment = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimeCommentBytes();

  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  java.util.List<web.api.rpc.newsfeed.ChildComment> 
      getChildCommentsList();
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  web.api.rpc.newsfeed.ChildComment getChildComments(int index);
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  int getChildCommentsCount();
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  java.util.List<? extends web.api.rpc.newsfeed.ChildCommentOrBuilder> 
      getChildCommentsOrBuilderList();
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  web.api.rpc.newsfeed.ChildCommentOrBuilder getChildCommentsOrBuilder(
      int index);
}
