// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.api.rpc.newsfeed;

public interface GetNewsFeedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetNewsFeedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Post posts = 1;</code>
   */
  java.util.List<web.api.rpc.newsfeed.Post> 
      getPostsList();
  /**
   * <code>repeated .Post posts = 1;</code>
   */
  web.api.rpc.newsfeed.Post getPosts(int index);
  /**
   * <code>repeated .Post posts = 1;</code>
   */
  int getPostsCount();
  /**
   * <code>repeated .Post posts = 1;</code>
   */
  java.util.List<? extends web.api.rpc.newsfeed.PostOrBuilder> 
      getPostsOrBuilderList();
  /**
   * <code>repeated .Post posts = 1;</code>
   */
  web.api.rpc.newsfeed.PostOrBuilder getPostsOrBuilder(
      int index);
}
