// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package web.api.rpc.chat;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromUser = 1;</code>
   */
  java.lang.String getFromUser();
  /**
   * <code>string fromUser = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromUserBytes();

  /**
   * <code>string toUser = 2;</code>
   */
  java.lang.String getToUser();
  /**
   * <code>string toUser = 2;</code>
   */
  com.google.protobuf.ByteString
      getToUserBytes();

  /**
   * <code>string content = 3;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
