// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package web.api.rpc.chat;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChannelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChannelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChannelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChannelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\"@\n\013ChatMessage\022\020\n\010fromUser\030" +
      "\001 \001(\t\022\016\n\006toUser\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\"5" +
      "\n\021GetChannelRequest\022\017\n\007userId1\030\001 \001(\t\022\017\n\007" +
      "userId2\030\002 \001(\t\"\"\n\022GetChannelResponse\022\014\n\004u" +
      "uid\030\001 \001(\t2D\n\013ChatService\0225\n\ngetChannel\022\022" +
      ".GetChannelRequest\032\023.GetChannelResponseB" +
      "\027\n\020web.api.rpc.chatP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatMessage_descriptor,
        new java.lang.String[] { "FromUser", "ToUser", "Content", });
    internal_static_GetChannelRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetChannelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChannelRequest_descriptor,
        new java.lang.String[] { "UserId1", "UserId2", });
    internal_static_GetChannelResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetChannelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChannelResponse_descriptor,
        new java.lang.String[] { "Uuid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
