// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package web.api.rpc.chat;

public interface GetChannelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetChannelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId1 = 1;</code>
   */
  java.lang.String getUserId1();
  /**
   * <code>string userId1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserId1Bytes();

  /**
   * <code>string userId2 = 2;</code>
   */
  java.lang.String getUserId2();
  /**
   * <code>string userId2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserId2Bytes();
}
